spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: admin
    password: 12345

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  jwt:
    secret: ThisIs@Very$Secure$SecretKeyWithSymbols123
    expiration: 86400000

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    enabled: true

logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG

    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
